Feature/TD-16/Тесты для LoginScene
djud17-org/todoList pull request #43
Opened 2023-03-28 15:17 UTC by zzzarya

2023-03-28 17:38 UTC, djud17 commented on taskManager/Scenes/Login/LoginInteractor.swift
> +
теперь параметры можно сделать приватными и константами)

2023-03-28 17:38 UTC, djud17 commented on taskManager/Scenes/Login/LoginViewController.swift
Аналогично) приватные константы)

2023-03-28 17:38 UTC, djud17 commented on taskManager/Scenes/Login/LoginViewController.swift
>  	}
ну по идее отдельная функция не нужна ж) в метод кнопки положи)

2023-03-28 17:38 UTC, djud17 commented on taskManagerTests/LoginScene/LoginViewControllerTests.swift
> +}
Надо проверить невалидные варианты тоже

2023-03-28 17:38 UTC, djud17 commented on taskManagerTests/LoginScene/LoginViewControllerTests.swift
> +		interactor = LoginInteractorSpy()
Ты же вроде убрал сториборды?

2023-03-28 17:38 UTC, djud17 commented on taskManagerTests/LoginScene/Test Doubles/LoginViewControllerSpy.swift
> +	// MARK: - Internal Properties
final

2023-03-28 17:38 UTC, djud17 commented on taskManagerTests/LoginScene/Test Doubles/LoginWorkerSpy.swift
> +	// MARK: - Internal Properties
final

2023-03-28 20:49 UTC, zzzarya commented on taskManager/Scenes/Login/LoginViewController.swift
Ругается ассемблер

2023-03-29 19:45 UTC, djud17 approved these changes

2023-03-30 07:30 UTC, SShliakhin requested changes
3 замечания + проверь структуру папок
я думаю, должно быть как то так:
<img width="244" alt="image" src="https://user-images.githubusercontent.com/71236551/228761818-88007bba-b598-464f-a1ac-6d55838c9087.png">

2023-03-30 07:30 UTC, SShliakhin commented on taskManagerTests/LoginScene/LoginInteractorTest.swift
Здесь конечно только один тест и ошибок не будет, а если будет два, то надо будет переделывать инициализацию worker и presenter, предлагаю:

```swift
        private var worker: LoginWorkerSpy! // swiftlint:disable:this implicitly_unwrapped_optional
	private var presenter: LoginPresenterSpy! // swiftlint:disable:this implicitly_unwrapped_optional

private extension LoginInteractorTests {
	func makeSut() -> LoginInteractor {
		worker = LoginWorkerSpy()
		presenter = LoginPresenterSpy()

		return LoginInteractor(worker: worker, presenter: presenter)
	}
}
```

2023-03-30 07:30 UTC, SShliakhin commented on taskManagerTests/LoginScene/LoginPresenterTests.swift
> +	private let viewController = LoginViewControllerSpy()
здесь тоже замечание, что и выше, имеем два теста, один зависит от другого, надо засовывать инициализацию viewController в makeSut()

2023-03-30 07:30 UTC, SShliakhin commented on taskManagerTests/LoginScene/LoginViewControllerTests.swift
> +}
Здесь проверяем вызов login() у интерактора, не имеет значение какие данные: валидные или невалидные, для ясности можно назвать тест: `test_login_shouldCalledInteractorLogin()`

2023-03-30 08:15 UTC, SShliakhin requested changes
Перед сдачей на ревью надо проверять конфликты на вливание, там должно быть зеленым - ветка после апрувов должна быть готова к вливанию автоматически.

2023-03-30 08:50 UTC, djud17 commented on taskManagerTests/LoginScene/LoginInteractorTest.swift
Отключение правил линтера не очень хорошая практика
Лучше не выдумывать и не делать лишнего)

2023-03-30 08:52 UTC, djud17 commented on taskManagerTests/LoginScene/LoginViewControllerTests.swift
> +}
Это уже обсудили в чате, все так) с названием теста согласен

2023-03-30 11:25 UTC, SShliakhin commented on taskManagerTests/LoginScene/LoginInteractorTest.swift
Тут ведь я на зависимости тестов друг от друга делаю упор, линтер побочка.

2023-03-30 11:45 UTC, SShliakhin approved these changes

2023-03-30 11:46 UTC, merged