TaskListPresenter has been covered by tests #40
djud17-org/todoList pull request #46
Opened 2023-03-29 13:14 UTC by chuRealOff

2023-03-29 16:25 UTC, AlexeyRadomskiy approved these changes

2023-03-29 19:48 UTC, djud17 commented on taskManagerTests/TaskListScene/TaskPresenterTests.swift
> +		let dataModel = TaskListModel.ResponseDataModel(sections: section)
1. По идее же можно передать пустые данные в presenter? чтоб не тащить сюда пакет
2. Если же нет, то предлагаю всю подготовку данных перенести в метод makeSut

2023-03-30 07:54 UTC, SShliakhin requested changes
Есть замечания и предложения

2023-03-30 07:54 UTC, SShliakhin commented on taskManagerTests/TaskListScene/Test Doubles/TaskListViewControllerSpy.swift
Можно проверить еще данные которые будем рендрить, картинка из моего проекта
<img width="686" alt="image" src="https://user-images.githubusercontent.com/71236551/228766677-d39aaf5f-1010-4634-8eb7-3128b2bf6d6e.png">

2023-03-30 07:54 UTC, SShliakhin commented on taskManagerTests/TaskListScene/TaskPresenterTests.swift
Замечание по инициализации шпиона, пока тест один, все норм, будет два - появится зависимость одного от другого. Привожу пример с дополнительными проверками и другой инициализацией:
<img width="873" alt="image" src="https://user-images.githubusercontent.com/71236551/228767428-dceceea5-52be-48c5-977c-b6f1fc956fd7.png">

2023-03-30 07:54 UTC, SShliakhin commented on taskManagerTests/TaskListScene/TaskPresenterTests.swift
> +	func test_displayData_shouldSucceed() {
в наименовании не учтены параметры, может быть так: `test_displayData_withOneSectionAndTwoTasks_shouldBeRenderSuccess`

2023-03-30 08:58 UTC, djud17 commented on taskManagerTests/TaskListScene/TaskPresenterTests.swift
А как у тебя проходят данные тесты, если ты инициализируешь в шпионе пустой массив?

2023-03-30 09:00 UTC, djud17 commented on taskManagerTests/TaskListScene/Test Doubles/TaskListViewControllerSpy.swift
Проверить стоит, но как и писал выше - не понимаю как проходят тесты, если у тебя здесь пустая вью модель

2023-03-30 09:10 UTC, chuRealOff commented on taskManagerTests/TaskListScene/TaskPresenterTests.swift
> +		let dataModel = TaskListModel.ResponseDataModel(sections: section)
Да, действительно. Удалось передать презентеру пустой массив дата модели, что помогло избавиться от пакета

2023-03-30 09:11 UTC, SShliakhin commented on taskManagerTests/TaskListScene/TaskPresenterTests.swift
при тесте `sut.present(responce: response)` я его заполняю в render: `viewModel = viewData`

2023-03-30 09:41 UTC, chuRealOff commented on taskManagerTests/TaskListScene/TaskPresenterTests.swift
согласен. Изменения отражены в новой редакции

2023-03-30 10:59 UTC, chuRealOff commented on taskManagerTests/TaskListScene/TaskPresenterTests.swift
> +	func test_displayData_shouldSucceed() {
наименование метода не менял, так как решил не тестировать наполнение дата модели сущностями по той причине, что эти тесты будет невозможно провалить в каждом отдельно взятом случае.
Вдобавок, данные тесты потребовали бы импортировать наш TaskManagerPackage фреймворк в тестовый класс для того чтобы иметь беспрепятственный доступ к классам заданий.

2023-03-30 11:00 UTC, chuRealOff commented on taskManagerTests/TaskListScene/TaskPresenterTests.swift
> +	func test_displayData_shouldSucceed() {
предложенное решение понравилось. Благодарю за фидбек!

2023-03-30 11:20 UTC, SShliakhin requested changes

2023-03-30 11:20 UTC, SShliakhin commented on taskManagerTests/TaskListScene/TaskPresenterTests.swift
> +	func test_displayData_shouldSucceed() {
Наверно, параметр если пустой, то наверно можно и опусить в имени. А можно было и вставить withEmptyModel - не влияет на ревью для меня

2023-03-30 11:20 UTC, SShliakhin commented on taskManagerTests/TaskListScene/Test Doubles/TaskListViewControllerSpy.swift
> +	private(set) var viewModel = TaskListModel.ViewModel(tasksBySections: [])
тогда зачем ты здесь это объявляешь если не планируешь использовать?

2023-03-30 11:32 UTC, chuRealOff commented on taskManagerTests/TaskListScene/Test Doubles/TaskListViewControllerSpy.swift
> +	private(set) var viewModel = TaskListModel.ViewModel(tasksBySections: [])
пробовал внедрить идею, но не избавился от всех следов.

2023-03-30 12:14 UTC, SShliakhin approved these changes

2023-03-30 12:14 UTC, SShliakhin commented on taskManagerTests/TaskListScene/Test Doubles/TaskListViewControllerSpy.swift
Я так понял мы решили не проверять, ок. даю аппрув.

2023-03-30 12:16 UTC, merged

2023-03-30 12:17 UTC, SShliakhin approved these changes