feat(TD-19): Добавлены тесты для TaskListViewController
djud17-org/todoList pull request #47
Opened 2023-03-29 16:23 UTC by AlexeyRadomskiy

2023-03-29 19:54 UTC, djud17 commented on taskManagerTests/TaskList/TaskListViewControllerTests.swift
> +
Всю подготовку выносим в метод makeSut в private extension

2023-03-29 19:54 UTC, djud17 commented on taskManagerTests/TaskList/TaskListViewControllerTests.swift
> +class TaskListInteractorSpy: ITaskListBusinessLogic {
Final
+ лучше вынести в отдельный файл
1 файл = 1 сущность

2023-03-30 09:16 UTC, SShliakhin requested changes

2023-03-30 09:16 UTC, SShliakhin commented on taskManagerTests/TaskList/TaskListViewControllerTests.swift
> +class TaskListInteractorSpy: ITaskListBusinessLogic {
согласен

2023-03-30 09:16 UTC, SShliakhin commented on taskManagerTests/TaskList/TaskListViewControllerTests.swift
> +
согласен с предложением Давида

2023-03-30 17:54 UTC, AlexeyRadomskiy commented on taskManagerTests/TaskList/TaskListViewControllerTests.swift
> +
в данном случае считаю в этом нет необходимости, мне нужно создать и использовать VC и Interactor.
Если выносить в отдельный метод, с возвращаемым параметром VC, то нужно внутрь прокидывать interactor, а если экземпляр передавать извне, то инициализировать придется все равно в setUp, как sut, так и spy.

Считаю это усложнением кода, и можно оставить создание в методе setUp()

2023-03-30 17:57 UTC, AlexeyRadomskiy commented on taskManagerTests/TaskList/TaskListViewControllerTests.swift
> +class TaskListInteractorSpy: ITaskListBusinessLogic {
вынес

2023-03-30 17:58 UTC, AlexeyRadomskiy commented on taskManagerTests/TaskList/TaskListViewControllerTests.swift
> +class TaskListInteractorSpy: ITaskListBusinessLogic {
> согласен с предложением Давида

лучше так не писать, это лишний комментарий без дополнения. Выше аналогично.

2023-03-30 18:48 UTC, SShliakhin requested changes
Замечания по наименованию + версия Xcode и одно предложение

2023-03-30 18:48 UTC, SShliakhin commented on taskManager.xcodeproj/project.pbxproj
> +	objectVersion = 56;
Здесь тебе надо подправить на 55, чтобы не перезалить поддержку моего Xcode

2023-03-30 18:48 UTC, SShliakhin commented on taskManagerTests/TaskListScene/TaskListViewControllerTests.swift
> +	func test_viewDidLoad_callsInteractor_viewIsReady() {
немного нарушил правило наименования метода: callsInteractor_viewIsReady надо слить в callsInteractorViewIsReady

2023-03-30 18:48 UTC, SShliakhin commented on taskManagerTests/TaskListScene/TaskListViewControllerTests.swift
> +	func test_didSelectRowAt_callsInteractor_didTaskSelected() {
тут с наименованием тоже не очень, у нас есть параметры, в имени их нет, а концовку также склеить как в примере выше.

2023-03-30 18:48 UTC, SShliakhin commented on taskManagerTests/TaskListScene/TaskListViewControllerTests.swift
По ссылке на тесты CS, которую скидывал нам Кирилл, есть пример теста метода render, я его реализовал, прикладываю картинку, хочешь тоже реализуй, но тебе надо еще сделать шпиона для таблицы.
<img width="1251" alt="image" src="https://user-images.githubusercontent.com/71236551/228934206-efed1755-c80b-423e-a0a1-ecd4dae9c90a.png">
<img width="738" alt="image" src="https://user-images.githubusercontent.com/71236551/228934488-576355ad-be6d-49b5-bd4f-648cee46cdcd.png">

2023-03-30 19:10 UTC, AlexeyRadomskiy commented on taskManager.xcodeproj/project.pbxproj
> +	objectVersion = 56;
Можно подробней, как это может перезалить поддержку твоего Xcode?

2023-03-30 19:12 UTC, AlexeyRadomskiy commented on taskManagerTests/TaskListScene/TaskListViewControllerTests.swift
> +	func test_viewDidLoad_callsInteractor_viewIsReady() {
после слова test  я пишу названия метода, который тестирую.
Далее говорю что делает мой тест и какой результат ожидаю.
Я вызываю интерактор, ожидаю что вью будет загружена

А не говорю интерактору загрузить вью. Интерактор все что знает, это то что вью была загружена.
Зачем лепить все в кучу?

2023-03-30 19:13 UTC, AlexeyRadomskiy commented on taskManagerTests/TaskListScene/TaskListViewControllerTests.swift
> +	func test_didSelectRowAt_callsInteractor_didTaskSelected() {
Смотри комментарии выше

2023-03-30 19:15 UTC, AlexeyRadomskiy commented on taskManagerTests/TaskListScene/TaskListViewControllerTests.swift
тест презентира уже покрывает данную логику

2023-03-30 19:18 UTC, SShliakhin commented on taskManagerTests/TaskListScene/TaskListViewControllerTests.swift
> +	func test_viewDidLoad_callsInteractor_viewIsReady() {
Не знаю) такой нам дали стайл гайд, тогда мне тоже дайте новые установки, а то я новенький

2023-03-30 19:19 UTC, SShliakhin commented on taskManager.xcodeproj/project.pbxproj
> +	objectVersion = 56;
твой код поменяет 55 на 56, мне надо чтобы осталось 55

2023-03-30 19:20 UTC, SShliakhin commented on taskManagerTests/TaskListScene/TaskListViewControllerTests.swift
я только предложил

2023-03-30 19:26 UTC, AlexeyRadomskiy commented on taskManagerTests/TaskListScene/TaskListViewControllerTests.swift
> +	func test_viewDidLoad_callsInteractor_viewIsReady() {
Вот что было в той документации.

```swift
func test_incrementScanCount_withInProgressItemModel_shouldBeFail()
```

1. `test` - начало тестовой функции;
2. `incrementScanCount` - тестируемая функция;
3. `withInProgressItemModel` - параметры тестирования (если нужны);
4. `shouldBeFail` - ожидаемый результат теста.

3 - _callsInteractor - в качестве параметра выступает интерактор
4- _viewIsReady - ожидаю что вью будет готова

2023-03-30 19:36 UTC, AlexeyRadomskiy commented on taskManager.xcodeproj/project.pbxproj
> +	objectVersion = 56;
вернул

2023-03-30 20:07 UTC, SShliakhin requested changes

2023-03-30 20:07 UTC, SShliakhin commented on taskManagerTests/TaskListScene/TaskListViewControllerTests.swift
> +	func test_viewDidLoad_callsInteractor_viewIsReady() {
смотри, под параметрами я понимаю параметры, которые передаются в метод, здесь параметры отсутствуют sut.viewDidLoad(), т.е. наименование тестового метода по гайду должно состоять из 3 частей. А callsInteractorViewReady - это результат который мы ожидаем: вызвать метод интерактора ViewReady, пусть без ожидания, я согласен

2023-03-30 20:07 UTC, djud17 commented on taskManagerTests/TaskList/TaskListViewControllerTests.swift
> +
Кирилл в лекции говорил, что убираем setup и teardown, всю подготовку переносим в метод makeSut в private extension. По аналогии с другими тестами

2023-03-30 20:10 UTC, djud17 commented on taskManagerTests/TaskListScene/Test Doubles/TaskListInteractorSpy.swift
> +	private(set) var viewIsReadyCalled = false
final

2023-03-30 20:10 UTC, djud17 commented on taskManagerTests/TaskListScene/TaskListViewControllerTests.swift
> +	}
указал аргументацию в комментариях, makeSut

2023-03-31 19:35 UTC, SShliakhin approved these changes
Все опционально, если хочешь обсудить, то предлагаю в чате.

2023-03-31 19:35 UTC, SShliakhin commented on taskManager.xcodeproj/project.pbxproj
> +				TARGETED_DEVICE_FAMILY = 1;
Для информации: а здесь мы для чего меняем?

2023-03-31 19:35 UTC, SShliakhin commented on taskManagerTests/TaskListScene/TaskListViewControllerTests.swift
> +		XCTAssertTrue(interactorSpy.viewIsReadyCalled, "Метод отработал некорректно")
"Метод interactor viewIsReady() не был вызван" - опционально, я не знаю какая наша политика партии)

2023-03-31 19:35 UTC, SShliakhin commented on taskManagerTests/TaskListScene/TaskListViewControllerTests.swift
> +		XCTAssertTrue(interactorSpy.didTaskSelectedCalled, "Некорректный вызов метода")
"Метод interactor didTaskSelected() не был вызван" - опционально, я не знаю какая наша политика партии)

2023-03-31 19:35 UTC, SShliakhin commented on taskManagerTests/TaskListScene/TaskListViewControllerTests.swift
> +		XCTAssertEqual(interactorSpy.selectedTaskIndexPath, indexPath, "Метод возвращет некорректный IndexPath")
я бы не так тестировал, мои пробные предложения не находили отклика, поэтому здесь ничего не предлагаю, но по твоему варианту: 
- имя метода:  test_didSelectRowAt_withTaskIndexPath_callsInteractorDidTaskSelected
- ассет: "Переданный IndexPath не соответствует принятому"
Опционально.

2023-03-31 19:52 UTC, djud17 approved these changes

2023-03-31 19:52 UTC, djud17 commented on taskManagerTests/TaskListScene/TaskListViewControllerTests.swift
> +		XCTAssertTrue(interactorSpy.didTaskSelectedCalled, "Некорректный вызов метода")
Ну тут наверное не то что некорректный вызов, а что какой то метод интерактора не был вызван
Что то типо такого
"У Presenter не был вызван метод displayData(data:)"

2023-03-31 19:52 UTC, djud17 commented on taskManagerTests/TaskListScene/TaskListViewControllerTests.swift
> +		XCTAssertTrue(interactorSpy.viewIsReadyCalled, "Метод отработал некорректно")
Аналогично, по примеру
"У Presenter не был вызван метод displayData(data:)"

2023-03-31 19:55 UTC, merged