TD-23 Поправлена верстка TaskListScene с помощью PinLayout
djud17-org/todoList pull request #59
Opened 2023-04-01 17:15 UTC by djud17

2023-04-01 19:36 UTC, SShliakhin requested changes
Замечания:
- private
- contentView вместо backView
- запах чисел
- наименование
- ложная оптимизация

2023-04-01 19:36 UTC, SShliakhin commented on taskManager/Scenes/TaskList/View/Cell/ImportantTask/ImportantTaskTableViewCell.swift
>  		label.setContentHuggingPriority(.init(250), for: .horizontal)
не понимаю, зачем это здесь?

2023-04-01 19:36 UTC, SShliakhin commented on taskManager/Scenes/TaskList/View/Cell/ImportantTask/ImportantTaskTableViewCell.swift
>  	lazy var taskNameLabel: UILabel = {
private lazy var

2023-04-01 19:36 UTC, SShliakhin commented on taskManager/Scenes/TaskList/View/Cell/ImportantTask/ImportantTaskTableViewCell.swift
>  	lazy var taskDeadlineLabel: UILabel = {
private lazy var

2023-04-01 19:36 UTC, SShliakhin commented on taskManager/Scenes/TaskList/View/Cell/ImportantTask/ImportantTaskTableViewCell.swift
> +	lazy var taskImportanceView = UIImageView()
private lazy var

2023-04-01 19:36 UTC, SShliakhin commented on taskManager/Scenes/TaskList/View/Cell/ImportantTask/ImportantTaskTableViewCell.swift
>  	lazy var backView: UIView = {
private

2023-04-01 19:36 UTC, SShliakhin commented on taskManager/Scenes/TaskList/View/Cell/ImportantTask/ImportantTaskTableViewCell.swift
> +			.height(20)
20 просит вынести в константы

2023-04-01 19:36 UTC, SShliakhin commented on taskManager/Helpers/Constants.swift
>  		static let fieldHeight: CGFloat = 40
вот в очередной раз читаю этот код и забыл к чему он, может быть все же как то по другому назовем или будем использовать абстрактные размеры?

2023-04-01 19:36 UTC, SShliakhin commented on taskManager/Scenes/TaskList/View/Cell/RegularTask/RegularTaskTableViewCell.swift
>  		let mediumOffset = Constants.Offset.mediumOffset
это просто лишние строчки, оптимизации нет, надо будет постоянно подымать глаза чтобы вспомнить что значит smallOffset или mediumOffset (я вообразил сложный лайаут). По мне лучше писать полностью по месту использования. Опционально.

2023-04-01 19:36 UTC, SShliakhin commented on taskManager/Scenes/TaskList/View/Cell/ImportantTask/ImportantTaskTableViewCell.swift
> +			.bottom(mediumOffset)
может быть так:
```swift
.left(mediumOffset)
.center()
.width(20)
.height(20)
```

20 просится в константы

2023-04-01 19:36 UTC, SShliakhin commented on taskManager/Scenes/TaskList/View/Cell/ImportantTask/ImportantTaskTableViewCell.swift
>  		let largeOffset = Constants.Offset.largeOffset
это просто лишние строчки, оптимизации нет, надо будет постоянно подымать глаза чтобы вспомнить что значит smallOffset или mediumOffset (я вообразил сложный лайаут). По мне лучше писать полностью по месту использования. Опционально

2023-04-01 19:36 UTC, SShliakhin commented on taskManager/Scenes/TaskList/View/Cell/RegularTask/RegularTaskTableViewCell.swift
>  	lazy var taskNameLabel: UILabel = {
private

2023-04-01 19:36 UTC, SShliakhin commented on taskManager/Scenes/TaskList/View/Cell/RegularTask/RegularTaskTableViewCell.swift
здесь backView совсем не нужно
у cell есть contentView в который надо добавляться

2023-04-01 19:36 UTC, SShliakhin commented on taskManager/Scenes/TaskList/View/Cell/ImportantTask/ImportantTaskTableViewCell.swift
здесь backView совсем не нужно
у cell есть contentView в который надо добавляться

2023-04-01 20:36 UTC, djud17 commented on taskManager/Helpers/Constants.swift
>  		static let fieldHeight: CGFloat = 40
Не совсем понимаю про что ты? Это константы, которые используются в приложении - размеры, отступы, цвета.

2023-04-01 20:38 UTC, djud17 commented on taskManager/Scenes/TaskList/View/Cell/ImportantTask/ImportantTaskTableViewCell.swift
Можно добавлять куда угодно) BackView был использован для удобства и дизайна

2023-04-01 20:38 UTC, djud17 commented on taskManager/Scenes/TaskList/View/Cell/ImportantTask/ImportantTaskTableViewCell.swift
>  	lazy var taskNameLabel: UILabel = {
Private здесь невозможен, так как мы настраиваем ячейку снаружи и нам нужен доступ к ее полям

2023-04-01 20:39 UTC, djud17 commented on taskManager/Scenes/TaskList/View/Cell/ImportantTask/ImportantTaskTableViewCell.swift
>  		label.setContentHuggingPriority(.init(250), for: .horizontal)
Осталось от прошлых наработок) убрал

2023-04-01 20:39 UTC, djud17 commented on taskManager/Scenes/TaskList/View/Cell/ImportantTask/ImportantTaskTableViewCell.swift
>  	lazy var taskDeadlineLabel: UILabel = {
Объяснил выше

2023-04-01 20:40 UTC, djud17 commented on taskManager/Scenes/TaskList/View/Cell/ImportantTask/ImportantTaskTableViewCell.swift
> +	lazy var taskImportanceView = UIImageView()
Объяснил выше

2023-04-01 20:41 UTC, djud17 commented on taskManager/Scenes/TaskList/View/Cell/ImportantTask/ImportantTaskTableViewCell.swift
>  	lazy var backView: UIView = {
Здесь это можно и нужно добавить. Поправил

2023-04-01 20:42 UTC, djud17 commented on taskManager/Scenes/TaskList/View/Cell/ImportantTask/ImportantTaskTableViewCell.swift
>  		let largeOffset = Constants.Offset.largeOffset
Это увеличивает длину строчки.
Зачем поднимать глаза?) переменная называется mediumOffset и константа также называется, все логично на мой взгляд

2023-04-01 20:45 UTC, djud17 commented on taskManager/Scenes/TaskList/View/Cell/ImportantTask/ImportantTaskTableViewCell.swift
> +			.bottom(mediumOffset)
если это к taskImportanceView то нам он не нужен по центру ячейки. Зачем ставить в центр?
20 вынес в константы

2023-04-01 20:45 UTC, djud17 commented on taskManager/Scenes/TaskList/View/Cell/ImportantTask/ImportantTaskTableViewCell.swift
> +			.height(20)
Поправил

2023-04-01 20:46 UTC, djud17 commented on taskManager/Scenes/TaskList/View/Cell/RegularTask/RegularTaskTableViewCell.swift
Уже писал выше про это

2023-04-01 20:49 UTC, djud17 commented on taskManager/Scenes/TaskList/View/Cell/RegularTask/RegularTaskTableViewCell.swift
>  		let mediumOffset = Constants.Offset.mediumOffset
Как и писал выше это упрощает чтение кода. Эти константы используются во многих местах. Намного проще читать короткое smallOffset или mediumOffset, чем каждый раз Constants.Offset.smallOffset или Constants.Offset.mediumOffset.

2023-04-01 21:11 UTC, SShliakhin commented on taskManager/Helpers/Constants.swift
>  		static let fieldHeight: CGFloat = 40
я конкретно про fieldHeight - высота поля

2023-04-01 21:13 UTC, djud17 commented on taskManager/Helpers/Constants.swift
>  		static let fieldHeight: CGFloat = 40
не придумал другого названия) если есть идеи - предлагай)

2023-04-01 21:21 UTC, SShliakhin commented on taskManager/Helpers/Constants.swift
>  		static let fieldHeight: CGFloat = 40
я уже предлагал в другом месте, ты оставил так. Я еще раз увидел и маякнул, что не помню таких объектов в нашем проекте.

2023-04-01 21:40 UTC, SShliakhin requested changes
посмотри, пожалуйста про contentView у cell

2023-04-01 21:40 UTC, SShliakhin commented on taskManager/Scenes/TaskList/View/Cell/ImportantTask/ImportantTaskTableViewCell.swift
у VC есть корневое view, ты добавляешь к view
у cell есть корневое contentView, ты создаешь backView и куда ты добавляешь?

2023-04-01 21:40 UTC, SShliakhin commented on taskManager/Scenes/TaskList/View/Cell/ImportantTask/ImportantTaskTableViewCell.swift
>  	lazy var taskNameLabel: UILabel = {
я купился на сокрытие типов по вьюмодель, а ты оказывается его не используешь, ок, тогда да, private нельзя

2023-04-01 21:40 UTC, SShliakhin commented on taskManager/Scenes/TaskList/View/Cell/ImportantTask/ImportantTaskTableViewCell.swift
>  	lazy var taskDeadlineLabel: UILabel = {
ок

2023-04-01 21:40 UTC, SShliakhin commented on taskManager/Scenes/TaskList/View/Cell/ImportantTask/ImportantTaskTableViewCell.swift
> +	lazy var taskImportanceView = UIImageView()
ок

2023-04-01 21:40 UTC, SShliakhin commented on taskManager/Scenes/TaskList/View/Cell/ImportantTask/ImportantTaskTableViewCell.swift
> +			.bottom(mediumOffset)
вытянутый рисунок же получается, я предложил добавить высоту = ширине и разместить по центру, мне показалось так выглядит симпатичнее, ну ладно, пусть остается вытянутым, еще раз высоту ячейки увеличишь, будет заметнее)

2023-04-01 22:43 UTC, djud17 commented on taskManager/Scenes/TaskList/View/Cell/ImportantTask/ImportantTaskTableViewCell.swift
> +			.bottom(mediumOffset)
как ты себе представляешь верстку в таком случае? лейбл будет поверх картинки по центру? или под ней?
про высоту ячейки это сарказм или что?

2023-04-01 22:44 UTC, djud17 commented on taskManager/Scenes/TaskList/View/Cell/ImportantTask/ImportantTaskTableViewCell.swift
ты можешь добавлять элементы куда посчитаешь нужным, хоть на view, хоть на view во view. 
То что у ячейки есть contentView я прекрасно знаю, backView используется как контейнер, для более удобной настройки и конфигурации.

2023-04-02 07:58 UTC, SShliakhin approved these changes

2023-04-02 13:35 UTC, zzzarya approved these changes

2023-04-02 14:25 UTC, merged