LoginVC layout redesigned with PinLayout
djud17-org/todoList pull request #60
Opened 2023-04-02 18:30 UTC by chuRealOff

2023-04-02 19:37 UTC, djud17 requested changes

2023-04-02 19:37 UTC, djud17 commented on taskManager/Scenes/Login/LoginViewController.swift
> +import SwiftUI
а SwiftUI для чего?

2023-04-02 19:37 UTC, djud17 commented on taskManager/Scenes/Login/LoginViewController.swift
> +			.top(200)
вытащи 200 в константы

2023-04-02 19:37 UTC, djud17 commented on taskManager/Scenes/Login/LoginViewController.swift
> +
Tamiс не нужен

2023-04-02 19:37 UTC, djud17 commented on taskManager/Scenes/Login/LoginViewController.swift
> +
Tamiс не нужен

2023-04-02 19:37 UTC, djud17 commented on taskManager/Scenes/Login/LoginViewController.swift
> +
Tamiс не нужен

2023-04-03 07:50 UTC, chuRealOff commented on taskManager/Scenes/Login/LoginViewController.swift
> +import SwiftUI
хотел воспользоваться вьювером в соседнем окне для отслеживания изменений в реальном времени. 
Забыл удалить SwiftUI

2023-04-03 07:51 UTC, chuRealOff commented on taskManager/Scenes/Login/LoginViewController.swift
> +
напомни пожалуйста, почему здесь нет необходимости в использовании tamic?

2023-04-03 07:57 UTC, chuRealOff commented on taskManager/Scenes/Login/LoginViewController.swift
> +			.top(200)
сделал

2023-04-03 08:37 UTC, djud17 commented on taskManager/Scenes/Login/LoginViewController.swift
> +
потому что он для констрейтов, а мы верстаем на фреймах по сути.

2023-04-03 08:42 UTC, djud17 commented on taskManager/Scenes/Login/LoginViewController.swift
>  		}
Поправь везде пожалуйста, не увидел сразу
Если для `get` и/или `set` выражение простое и не превышает лимит длины строки, то оно записывается в одну строку.

2023-04-03 08:42 UTC, djud17 commented on taskManager/Scenes/Login/LoginViewController.swift
> +		let upperPadding = Constants.Offset.largeOffset * 15
Не очень хорошее решение, прицеплять к константе, которая отвечает за другой отступ. Если нам понадобиться поменять большой отступ - все поплывет здесь. Лучше отдельной константой вынеси

2023-04-03 09:00 UTC, zzzarya approved these changes

2023-04-03 09:00 UTC, zzzarya commented on taskManager/Scenes/Login/LoginViewController.swift
> +		button.layer.cornerRadius = 10
Здесь вопрос. Константу для радиуса тоже выносим или так оставляем?

2023-04-03 09:00 UTC, zzzarya commented on taskManager/Scenes/Login/LoginViewController.swift
> +		button.setTitleColor(.white.withAlphaComponent(0.5), for: .highlighted)
Аналогично с константой для альфы. Выносим или нет?)

2023-04-03 09:01 UTC, djud17 commented on taskManager/Scenes/Login/LoginViewController.swift
> +		button.layer.cornerRadius = 10
По хорошему вынести надо)

2023-04-03 09:01 UTC, djud17 commented on taskManager/Scenes/Login/LoginViewController.swift
> +		button.setTitleColor(.white.withAlphaComponent(0.5), for: .highlighted)
Здесь лучше вынести не константу альфы, а сам цвет

2023-04-03 09:05 UTC, chuRealOff commented on taskManager/Scenes/Login/LoginViewController.swift
> +		let upperPadding = Constants.Offset.largeOffset * 15
согласен.

2023-04-03 09:06 UTC, chuRealOff commented on taskManager/Scenes/Login/LoginViewController.swift
> +		let upperPadding = Constants.Offset.largeOffset * 15
создал новое перечисление с отступами в константах и добавил туда новое значение

2023-04-03 09:07 UTC, chuRealOff commented on taskManager/Scenes/Login/LoginViewController.swift
>  		}
поправил

2023-04-03 09:10 UTC, chuRealOff commented on taskManager/Scenes/Login/LoginViewController.swift
> +		button.layer.cornerRadius = 10
спорный вопрос... С одной стороны, это вроде как красивее. С другой - раздувать наш файл с константами объектами, которые могут больше никогда и не потребоваться...
Я бы пока что оставил этот вопрос на дальнейшую перспективу.

2023-04-03 09:12 UTC, chuRealOff commented on taskManager/Scenes/Login/LoginViewController.swift
> +		button.setTitleColor(.white.withAlphaComponent(0.5), for: .highlighted)
не, оставим как есть.
У нас в константах есть готовые цвета. Это одно. 
Начать накачивать туда ещё и степени прозрачности, да ну. 😁

2023-04-03 09:14 UTC, djud17 approved these changes

2023-04-03 09:37 UTC, SShliakhin approved these changes
- upperPadding - я бы заменил на процент от всей высоты экрана
- По поводу локальных констант на глобальные константы - ложная оптимизация, на простом лайауте точно бессмысленны, на сложном - надо смотреть откуда изначально локальная константа пришла - на основе глобальной она или что-то там еще и не было ли там ошибок в объявлении.
- Я так и не понял Кирилла можно ли оставлять просмотр через SwiftUI в окончательном варианте VC?
- У себя cornerRadius я отправляю в константы (правда я называю это Theme и у меня там не только размеры)
-  private lazy var + create (я бы make использовал) - Отлично!

2023-04-03 10:55 UTC, chuRealOff commented
> * upperPadding - я бы заменил на процент от всей высоты экрана
> * По поводу локальных констант на глобальные константы - ложная оптимизация, на простом лайауте точно бессмысленны, на сложном - надо смотреть откуда изначально локальная константа пришла - на основе глобальной она или что-то там еще и не было ли там ошибок в объявлении.
> * Я так и не понял Кирилла можно ли оставлять просмотр через SwiftUI в окончательном варианте VC?
> * У себя cornerRadius я отправляю в константы (правда я называю это Theme и у меня там не только размеры)
> * private lazy var + create (я бы make использовал) - Отлично!

Идею с процентами поддерживаю. Здорово

2023-04-03 11:03 UTC, merged

2023-04-03 11:03 UTC, chuRealOff commented
Большая часть предложений и пожеланий была учтена. 
Спасибо за работу!