TD-30 Реализовать ScreenObject для LoginScene
djud17-org/todoList pull request #77
Opened 2023-04-10 17:33 UTC by zzzarya

Так же добавил BaseScreenObject, можно от него наследоваться

2023-04-11 16:53 UTC, djud17 requested changes

2023-04-11 16:53 UTC, djud17 commented on taskManagerTests/Common/BaseScreenObject.swift
> +
отступ лишний

2023-04-11 16:53 UTC, djud17 commented on taskManagerTests/Common/BaseScreenObject.swift
> +}
Отсутствует документация для публичных методов
Переработал бы названия методов, чтоб было однозначно понятно за что они отвечают

2023-04-11 16:53 UTC, djud17 commented on taskManagerTests/LoginScene/LoginScreenObject.swift
> +class LoginScreenObject: BaseScreenObject {
final

2023-04-11 16:53 UTC, djud17 commented on taskManagerTests/LoginScene/LoginScreenObject.swift
> +}
Отсутствует документация для публичных методов
Также я бы переработал названия методов, из названия непонятно за что отвечает метод

2023-04-12 12:04 UTC, chuRealOff approved these changes

2023-04-12 15:58 UTC, SShliakhin approved these changes

2023-04-12 18:41 UTC, SShliakhin commented on taskManagerTests/LoginScene/LoginScreenObject.swift
> +}
@djud17 Хорошо бы было увидеть твои пожелания или требования к наименованию, а то так можно долго ревьюить/договариваться.

2023-04-14 09:01 UTC, djud17 approved these changes

2023-04-14 09:02 UTC, merged