TD-32 Созданы UI тесты для LoginScene
djud17-org/todoList pull request #78
Opened 2023-04-14 20:03 UTC by djud17

Добавлены тесты, проверяющие:
 - авторизацию с неверными credentials;
 - авторизацию с верными credentials;

2023-04-14 20:46 UTC, SShliakhin requested changes

2023-04-14 20:46 UTC, SShliakhin commented on taskManagerUITests/LoginScreen/LoginUITests.swift
> +	func test_login_withValidCred_mustBeSuccessed() {
я думаю лучше писать полностью или заменить на более короткое имя ..._withValidData_... и в конце я бы тоже не был так категоричен), по мне лучше shouldBeSuccess
Странно, что Кирилл не предложил нам зафиксить переход на следующий экран это было бы более логично.

2023-04-14 20:46 UTC, SShliakhin commented on taskManagerUITests/LoginScreen/LoginUITests.swift
> +	func test_login_withInValidCred_mustBeSuccessed() {
здесь, сложнее, есть ошибка/опечатка ..._withInvalidData_... и точно не успех, а что-то типа shouldBeShowErrorAlert

2023-04-14 21:02 UTC, djud17 commented on taskManagerUITests/LoginScreen/LoginUITests.swift
> +	func test_login_withInValidCred_mustBeSuccessed() {
Вот здесь не согласен. Показ алерта - не результат теста, тест на этом не заканчивается. Поэтому по сути здесь тоже должен быть успех, что тест не завалился ни на одном из этапов.

2023-04-14 21:04 UTC, djud17 commented on taskManagerUITests/LoginScreen/LoginUITests.swift
> +	func test_login_withValidCred_mustBeSuccessed() {
Названия тестов поправил. Что касается перехода согласен, но мне не пришло в голову как проверить это, у нас окно открывается модально, поэтому предыдущий контроллер живой и элементы его существуют..пробовал( если есть идеи как проверить - буду рад

2023-04-14 21:22 UTC, SShliakhin requested changes

2023-04-14 21:22 UTC, SShliakhin commented on taskManagerUITests/LoginScreen/LoginUITests.swift
> +	func test_login_withValidCredentials_shouldBeSuccessed() {
shouldBeSuccess - я не селен в английском, но такой вариант судя по авто переводу звучит лучше

2023-04-14 21:22 UTC, SShliakhin commented on taskManagerUITests/LoginScreen/LoginUITests.swift
> +	func test_login_withInValidCredentials_shouldBeSuccessed() {
ошибка осталась
по поводу что мы тестим, здесь по сценарию на неверные данные, должен появится алерт с ошибкой, а ты предлагаешь: читаю "Тест логина с неверными данными должен быть успешным", если взглянуть на предыдущий тест - там тоже самое но с верными данными, выглядят названия вместе странно.

2023-04-14 21:22 UTC, SShliakhin commented on taskManagerUITests/LoginScreen/LoginUITests.swift
> +	func test_login_withValidCredentials_shouldBeSuccessed() {
По поводу теста следующего экрана - можно проверить наличие TableView на нем и считаем, что мы залогинились корректно. Сможешь проверить его наличие?

2023-04-14 21:23 UTC, SShliakhin commented on taskManagerUITests/LoginScreen/LoginUITests.swift
> +	func test_login_withValidCred_mustBeSuccessed() {
по идее после успешного логина мы должны попасть на следующий экран.

2023-04-16 09:11 UTC, djud17 commented on taskManagerUITests/LoginScreen/LoginUITests.swift
> +	func test_login_withValidCred_mustBeSuccessed() {
это то понятно) вопрос в том, как это проверить?)

2023-04-16 09:16 UTC, djud17 commented on taskManagerUITests/LoginScreen/LoginUITests.swift
> +	func test_login_withValidCredentials_shouldBeSuccessed() {
Воспользуемся переводчиком)
shouldBeSuccessed - должен увенчаться успехом
shouldBeSuccess - должен быть успех
Не вижу существенной разницы) По смыслу на мой взгляд первый вариант звучит лучше.

2023-04-16 09:17 UTC, djud17 commented on taskManagerUITests/LoginScreen/LoginUITests.swift
> +	func test_login_withInValidCredentials_shouldBeSuccessed() {
Писал тебе уже в другой ветке, зачем дублировать?
Показ алерта - не результат теста, тест на этом не заканчивается. Поэтому по сути здесь тоже должен быть успех, что тест не завалился ни на одном из этапов.

2023-04-16 09:23 UTC, zzzarya approved these changes

2023-04-16 14:17 UTC, merged